name: Build Specific TDLib Version (v1.8.0)

on:
  workflow_dispatch:

jobs:
  build_tdlib_for_android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code (full depth)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install build dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          gperf clang cmake make git \
          zlib1g-dev \
          libssl-dev \
          openjdk-11-jdk
        echo "--- Installed versions ---"
        java -version
        cmake --version
        clang --version
        git --version
        echo "-------------------------"

    - name: Clone TDLib repository and checkout specific version
      run: |
        echo "Cloning TDLib repository..."
        git clone https://github.com/tdlib/td.git td
        cd td
        echo "Current directory: $(pwd)"
        echo "Fetching all tags from remote 'origin'..."
        git fetch origin --tags 
        echo "Checking out tag v1.8.0..."
        git checkout v1.8.0
        echo "Current TDLib version/tag after checkout:"
        git describe --tags

    - name: Configure and Build TDLib with JNI
      run: |
        cd td 
        mkdir -p build 
        cd build
        echo "Configuring CMake for TDLib JNI..."
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DTD_ENABLE_JNI=ON \
              -DCMAKE_INSTALL_PREFIX:PATH=../tdjni_install \ # Убрали комментарий с этой строки
              -DTD_ENABLE_LTO=ON \
              ..
        
        echo "Building ALL targets (this should include tdjni and generate Java sources)..."
        cmake --build . --config Release -j$(nproc)
        
        echo "Installing built libraries and headers (optional, but good for verification)..."
        cmake --install . --config Release

    - name: Build AAR using Gradle from TDLib example
      run: |
        cd td/example/java 
        echo "Building AAR with Gradle..."
        chmod +x ./gradlew 
        ./gradlew :tdlib:assembleRelease 

    - name: Upload AAR artifact
      uses: actions/upload-artifact@v4 
      with:
        name: tdlib-android-1.8.0-release.aar 
        path: td/example/java/tdlib/build/outputs/aar/tdlib-release.aar 
        if-no-files-found: error
