name: Test Logging

on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo Step
        run: echo "Hello, GitHub Actions! This is a log test."
      
      - name: Second Echo Step
        run: |
          echo "Line 1 of multiline echo."
          echo "Line 2 of multiline echo."
